<?php
$sstr=array(
':)',
':aah',
':angry',
':awas',
':ayo',
':babenangis',
':bajai',
':bedil',
':berak',
':bodem',
':bokong',
':bubuk',
':cape',
':cium',
':ckaka',
':D',
':dead',
':diam',
':dongkol',
':download',
':gelap',
':gitar',
':gitaran',
':good',
':goodluck',
':gosok',
':haaa',
':hemm',
':hi',
':he',
':hehe',
':help',
':huahua',
':huahaha',
':huh',
':hujan',
':hihi',
':hot',
':inul',
':jeep',
':jempol',
':jempol2',
':joged',
':kesel',
':lagu',
':lari',
':maaf',
':mabok',
':mancing',
':mbako',
':mikir',
':minum',
':mobil',
':moped',
':motor',
':motor1',
':mrengut',
':mumet',
':nangis',
':nemuide',
':newbie',
':newbiee',
':ngakak',
':ngamen',
':ngancam',
':ngece',
':ngejek',
':ngeledek',
':ngeledek2',
':ngeledek3',
':ngopi',
':nguli',
':ngupil',
':nocomment',
':nono',
':oke',
':ontel',
':oops',
':ckaka',
':P',
':palu',
':patroli',
':pentung',
':piss',
':rok',
':sakit',
':salaman',
':sedih',
':senang',
':senyum',
':sinis',
':sip',
':sleeping',
':ssst',
':stop',
':supir',
':tank',
':thx',
':top',
':topi',
':tos',
':udud',
':udut',
':upil',
':weee',
':week',
':welcome',
':wkaka',
':wkeke',
);
$simg=array(
'<img src="http://whiznoe.xtgem.com/smiley/senyum.gif" alt=")"/>',
'<img src="http://chodot.yn.lt/img/aah.gif" alt="aah"/>',
'<img src="http://chodot.yn.lt/img/angry.gif" alt="angry"/>',
'<img src="http://chodot.yn.lt/img/awas.gif" alt="awas"/>',
'<img src="http://chodot.yn.lt/img/ayo.gif" alt="ayo"/>',
'<img src="http://chodot.yn.lt/img/babenangis.gif" alt="babenangis"/>',
'<img src="http://chodot.yn.lt/img/bajai.gif" alt="bajai"/>',
'<img src="http://chodot.yn.lt/img/bedil.gif" alt="bedil"/>',
'<img src="http://chodot.yn.lt/img/berak.gif" alt="berak"/>',
'<img src="http://chodot.yn.lt/img/bodem.gif" alt="bodem"/>',
'<img src="http://chodot.yn.lt/img/bokong.gif" alt="bokong"/>',
'<img src="http://chodot.yn.lt/img/bubuk.gif" alt="bubuk"/>',
'<img src="http://chodot.yn.lt/img/cape.gif" alt="cape"/>',
'<img src="http://chodot.yn.lt/img/cium.gif" alt="cium"/>',
'<img src="http://chodot.yn.lt/img/ckaka.gif" alt="ckaka"/>',
'<img src="http://whiznoe.xtgem.com/smiley/D.gif" alt="D"/>',
'<img src="http://chodot.yn.lt/img/dead.gif" alt="dead"/>',
'<img src="http://chodot.yn.lt/img/diam.gif" alt="diam"/>',
'<img src="http://chodot.yn.lt/img/dongkol.gif" alt="dongkol"/>',
'<img src="http://chodot.yn.lt/img/download.gif" alt="download"/>',
'<img src="http://chodot.yn.lt/img/gelap.gif" alt="gelap"/>',
'<img src="http://chodot.yn.lt/img/gitar.gif" alt="gitar"/>',
'<img src="http://chodot.yn.lt/img/gitaran.gif" alt="gitaran"/>',
'<img src="http://chodot.yn.lt/img/good.gif" alt="good"/>',
'<img src="http://chodot.yn.lt/img/goodluck.gif" alt="goodluck"/>',
'<img src="http://chodot.yn.lt/img/gosok.gif" alt="gosok"/>',
'<img src="http://chodot.yn.lt/img/haaa.gif" alt="haaa"/>',
'<img src="http://chodot.yn.lt/img/hem.gif" alt="hem"/>',
'<img src="http://chodot.yn.lt/img/hi.gif" alt="hi"/>',
'<img src="http://chodot.yn.lt/img/he.gif" alt="he"/>',
'<img src="http://chodot.yn.lt/img/hehe.gif" alt="hehe"/>',
'<img src="http://chodot.yn.lt/img/help.gif" alt="help"/>',
'<img src="http://chodot.yn.lt/img/huahua.gif" alt="huahua"/>',
'<img src="http://chodot.yn.lt/img/huahaha.gif" alt="huahaha"/>',
'<img src="http://chodot.yn.lt/img/huh.gif" alt="huh"/>',
'<img src="http://chodot.yn.lt/img/hujan.gif" alt="hujan"/>',
'<img src="http://chodot.yn.lt/img/hihi.gif" alt="hihi"/>',
'<img src="http://chodot.yn.lt/img/hot.gif" alt="hot"/>',
'<img src="http://chodot.yn.lt/img/inul.gif" alt="inul"/>',
'<img src="http://chodot.yn.lt/img/jeep.gif" alt="jeep"/>',
'<img src="http://chodot.yn.lt/img/jempol.gif" alt="jempol"/>',
'<img src="http://chodot.yn.lt/img/jempol2.gif" alt="jempol2"/>',
'<img src="http://chodot.yn.lt/img/joget.gif" alt="joget"/>',
'<img src="http://chodot.yn.lt/img/kesel.gif" alt="kesel"/>',
'<img src="http://chodot.yn.lt/img/lagu.gif" alt="lagu"/>',
'<img src="http://chodot.yn.lt/img/lari.gif" alt="lari"/>',
'<img src="http://chodot.yn.lt/img/maaf.gif" alt="maaf"/>',
'<img src="http://chodot.yn.lt/img/mabok.gif" alt="mabok"/>',
'<img src="http://chodot.yn.lt/img/mancing.gif" alt="mancing"/>',
'<img src="http://chodot.yn.lt/img/mbako.gif" alt="mbako"/>',
'<img src="http://chodot.yn.lt/img/mikir.gif" alt="mikir"/>',
'<img src="http://chodot.yn.lt/img/minum.gif" alt="minum"/>',
'<img src="http://chodot.yn.lt/img/mobil.gif" alt="mobil"/>',
'<img src="http://chodot.yn.lt/img/moped.gif" alt="moped"/>',
'<img src="http://chodot.yn.lt/img/motor.gif" alt="motor"/>',
'<img src="http://chodot.yn.lt/img/motor1.gif" alt="motor1"/>',
'<img src="http://chodot.yn.lt/img/mrengut.gif" alt="mrengut"/>',
'<img src="http://chodot.yn.lt/img/mumet.gif" alt="mumet"/>',
'<img src="http://chodot.yn.lt/img/nangis.gif" alt="nangis"/>',
'<img src="http://chodot.yn.lt/img/nemuide.gif" alt="nemuide"/>',
'<img src="http://chodot.yn.lt/img/newbie.gif" alt="newbie"/>',
'<img src="http://chodot.yn.lt/img/newbiee.gif" alt="newbiee"/>',
'<img src="http://chodot.yn.lt/img/ngakak.gif" alt="ngakak"/>',
'<img src="http://chodot.yn.lt/img/ngamen.gif" alt="ngamen"/>',
'<img src="http://chodot.yn.lt/img/ngancam.gif" alt="ngancam"/>',
'<img src="http://chodot.yn.lt/img/ngece.gif" alt="ngece"/>',
'<img src="http://chodot.yn.lt/img/ngejek.gif" alt="ngejek"/>',
'<img src="http://chodot.yn.lt/img/ngeledek.gif" alt="ngeledek"/>',
'<img src="http://chodot.yn.lt/img/ngeledek2.gif" alt="ngeledek2"/>',
'<img src="http://chodot.yn.lt/img/ngeledek3.gif" alt="ngeledek3"/>',
'<img src="http://chodot.yn.lt/img/ngopi.gif" alt="ngopi"/>',
'<img src="http://chodot.yn.lt/img/nguli.gif" alt="nguli"/>',
'<img src="http://chodot.yn.lt/img/ngupil.gif" alt="ngupil"/>',
'<img src="http://chodot.yn.lt/img/nocomment.gif" alt="nocomment"/>',
'<img src="http://chodot.yn.lt/img/nono.gif" alt="nono"/>',
'<img src="http://chodot.yn.lt/img/oke.gif" alt="oke"/>',
'<img src="http://chodot.yn.lt/img/ontel.gif" alt="ontel"/>',
'<img src="http://chodot.yn.lt/img/oops.gif" alt="oops"/>',
'<img src="http://whiznoe.xtgem.com/smiley/P.gif" alt="P"/>',
'<img src="http://chodot.yn.lt/img/pacaran.gif" alt="pacaran"/>',
'<img src="http://chodot.yn.lt/img/palu.gif" alt="palu"/>',
'<img src="http://chodot.yn.lt/img/patroli.gif" alt="patroli"/>',
'<img src="http://chodot.yn.lt/img/pentung.gif" alt="pentung"/>',
'<img src="http://chodot.yn.lt/img/piss.gif" alt="piss"/>',
'<img src="http://chodot.yn.lt/img/rok.gif" alt="rok"/>',
'<img src="http://chodot.yn.lt/img/sakit.gif" alt="sakit"/>',
'<img src="http://chodot.yn.lt/img/salaman.gif" alt="salaman"/>',
'<img src="http://chodot.yn.lt/img/sedih.gif" alt="sedih"/>',
'<img src="http://chodot.yn.lt/img/senang.gif" alt="senang"/>',
'<img src="http://chodot.yn.lt/img/senyum.gif" alt="senyum"/>',
'<img src="http://chodot.yn.lt/img/sinis.gif" alt="sinis"/>',
'<img src="http://chodot.yn.lt/img/sip.gif" alt="sip"/>',
'<img src="http://chodot.yn.lt/img/sleeping.gif" alt="sleeping"/>',
'<img src="http://chodot.yn.lt/img/ssst.gif" alt="ssst"/>',
'<img src="http://chodot.yn.lt/img/stop.gif" alt="stop"/>',
'<img src="http://chodot.yn.lt/img/supir.gif" alt="supir"/>',
'<img src="http://chodot.yn.lt/img/tank.gif" alt="tank"/>',
'<img src="http://chodot.yn.lt/img/thx.gif" alt="thx"/>',
'<img src="http://chodot.yn.lt/img/top.gif" alt="top"/>',
'<img src="http://chodot.yn.lt/img/topi.gif" alt="topi"/>',
'<img src="http://chodot.yn.lt/img/tos.gif" alt="tos"/>',
'<img src="http://chodot.yn.lt/img/udud.gif" alt="udud"/>',
'<img src="http://chodot.yn.lt/img/udut.gif" alt="udut"/>',
'<img src="http://chodot.yn.lt/img/upil.gif" alt="upil"/>',
'<img src="http://chodot.yn.lt/img/weee.gif" alt="weee"/>',
'<img src="http://chodot.yn.lt/img/week.gif" alt="week"/>',
'<img src="http://chodot.yn.lt/img/welcome.gif" alt="welcome"/>',
'<img src="http://chodot.yn.lt/img/wkaka.gif" alt="wkaka"/>',
'<img src="http://chodot.yn.lt/img/wkeke.gif" alt="wkeke"/>',
);
?>
